### PR TITLE
SVGO optimization should be an option

### PR DESCRIPTION
**Pull request by jrauschenbusch**
Pull request for #325

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks!

**Comment by jrauschenbusch** [comment]
You're welcome!

Can you make a npm release with v1.2.1 or v1.3.0? Then i could update a project i'm currently working on.

Best regards!
Jochen

**Comment by sapegin** [comment]
@jrauschenbusch Done, sorry for the delay.

**Comment by jrauschenbusch** [comment]
@sapegin: Thanks!

**Pull request merged**
