### PR TITLE
update ttf2woff2 for node 4+ support

### PR DESCRIPTION
**Pull request by fernandopasik**
https://github.com/sapegin/grunt-webfont/issues/286

### CODE REVIEW

**Comment by sapegin** [comment]
Hm, it’s not a support, it’s a requirement. We should require node 4+ for grunt-webfont too.

**Comment by nfroidure** [comment]
Not anymore with the last ttf2woff2 update, in fact it is now compatible with at least Node 0.12. In all cases though, when the build fails the emscriten fallback still works.

**Comment by fernandopasik** [comment]
@sapegin can we bump grunt-webfont version and publish to npm also please?

**Comment by nfroidure** [comment]
We're about to make it build on windows too https://github.com/nfroidure/ttf2woff2/issues/13#issuecomment-155413000

Just wait a bit, we'll warn you asap.

**Comment by sapegin** [comment]
@fernandopasik I’d wait for Windows support too.

**Comment by fernandopasik** [comment]
Oh ok! Thanks @sapegin @nfroidure !

**Comment by sapegin** [comment]
@nfroidure Hey is it ready? ;-)

**Comment by nfroidure** [comment]
Not yet, i'm changing the emscripten build to use bindings and maybe avoid the AVG antivirus warning.

**Pull request merged**
